# Copyright 2023 The Khronos Group Inc.
# Copyright 2023 Valve Corporation
# Copyright 2023 LunarG, Inc.
#
# SPDX-License-Identifier: Apache-2.0

name: ci - Vulkan SC

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
    - sc_main

jobs:
  build_and_test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        config: [Debug, Release]
        os: [ ubuntu-20.04, ubuntu-22.04, windows-latest ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Install Python dependencies
        run: python3 -m pip install pyparsing
      - name: Test CMake Minimum
        if: matrix.os == 'ubuntu-20.04'
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: 3.17.2
      - run: cmake -S. -B build -D VUL_WERROR=ON -D BUILD_TESTS=ON -D CMAKE_BUILD_TYPE=${{matrix.config}} -D UPDATE_DEPS=ON -D VULKANSC=ON
      - run: cmake --build build --config ${{matrix.config}} --verbose
      - run: ctest -C ${{matrix.config}} --output-on-failure
        working-directory: build/

  generate_source:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        run: python3 -m pip install pyparsing
      - name: Generate source
        run: |
          scripts/update_deps.py --dir external --no-build --api vulkansc
          scripts/generate_source.py external/Vulkan-Headers/registry/ --api vulkansc
      - run: git diff --exit-code
