# Copyright 2023 The Khronos Group Inc.
# Copyright 2023 Valve Corporation
# Copyright 2023 LunarG, Inc.
# Copyright 2023 RasterGrid Kft.
#
# SPDX-License-Identifier: Apache-2.0

name: ci - Vulkan SC

on:
    push:
        branches:
            - '!main'
    pull_request:
        branches:
            - sc_main

jobs:
  build_and_test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        config: [Debug, Release]
        os: [ ubuntu-20.04, ubuntu-22.04, windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install Python dependencies
        run: python3 -m pip install pyparsing
      - name: Test CMake Minimum
        if: matrix.os == 'ubuntu-20.04'
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: 3.17.2
      - name: Configure
        run: cmake -S. -B build -D VUL_WERROR=ON -D BUILD_TESTS=ON -D CMAKE_BUILD_TYPE=${{matrix.config}} -D UPDATE_DEPS=ON -D VULKANSC=ON
      - name: Build
        run: cmake --build build --config ${{matrix.config}} --verbose
      - name: Tests
        working-directory: ./build
        run: ctest -C ${{matrix.config}} --output-on-failure
      - name: Install
        run: cmake --install build --prefix ${{ github.workspace }}/install --config ${{matrix.config}}
      - name: Test find_package support
        run: |
          cmake -S tests/find_package -B tests/find_package/build -D CMAKE_PREFIX_PATH="${{ github.workspace }}/install;${{ github.workspace }}/external/${{matrix.config}}/Vulkan-Headers/build/install" -D CMAKE_BUILD_TYPE=${{matrix.config}}
          cmake --build tests/find_package/build --config ${{matrix.config}} --verbose

  reuse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v1

  generate_source:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        run: python3 -m pip install pyparsing
      - name: Generate source
        run: |
          scripts/update_deps.py --dir external --no-build --api vulkansc
          scripts/generate_source.py external/Vulkan-Headers/registry/ --api vulkansc
      - run: git diff --exit-code
